www/js/main.js
I modified the Special Station functionality in the Firmware that supports RF and IP stations to also control a raw GPIO pin. In essence this allows you to bypass the shift register/triac/protection circuitry of the OSPi and directly control a spare RPi gpio pin and any connected homebrew relay hardware. The /cs api command allows the setting of GPIO station type, gpio pin and active low/high.
I have modified the Special Station UI (see attached below) to allow a station to be configured with an associated gpio pin and a flag to specify whether the hardware is active high or low.
Two areas that need some consideration:
1) GPIO Pin Contention - There in no validation of gpio usage in the Firmware but the UI restricts selection to avoid OSPi dedicated pins (i.e. shift register, RF, etc).
2) …
=> Add GPIO Station support

Gruntfile.js, www/js/main.js
Samer/Ray,
I have done three pull requests (one on Firmware, one on App and one on Weather) to add the ability to adjust the baseline weather conditions in the Zimmerman adjustment method. See forum thread https://opensprinkler.com/forums/topic/zimmerman-parameters/
- App - main.js, I have extended the showZimmermanAdjustmentOptions function to include three additional input fields to capture the reference temperature, humidity and daily rainfall. In addition, I have used weather.forecast.region to determine the locale and from that whether to display in metric or imperial. I am uncertain if that object is always defined and would like confirmation that it is therefore available for use. It is set when wunderground is enabled and is referenceable in Zimmerman function but perhaps there …
=> Added ability to set reference weather conditions (Temp, Rain, Humidty) to the Zimmerman adjustment method

www/js/main.js
Confirm that Firmware is at, or above, version 2.1.7 before enabling GPIO Station functionality and before allowing the user to set the baseline weather conditions for Zimmerman adjustment method.
=> Added version checking to ensure backward comparability for GPIO Stations and Zimm2 extensions

www/js/main.js
Deferring introduction of POST commands to a later firmware version to allow GPIO Stations and enhanced Zimmerman features to be released in Firmware version 2.1.7.
=> Push back introduction of POST commands until version 2.1.8

www/js/main.js
Added the ability to check minor version numbers when determining if features should be enabled. This allows new features to be added to Firmware with requiring a bump of the major version number as this would trigger a reset of the Firmware settings.
=> Included minor version number when checking Firmerware version number

www/css/main.css, www/js/main.js
There are changes across both Firmware and App to support this feature.
The HTTP Station is a simple extension of the existing handler routines in both App and Firmware. This is very similar to the Remote Station code and allows the user to send HTTP GET commands to a server by configuring the following settings { Server, Port, On command, Off command }.
I have used a simple comma separated string to hold the above four parameters when transferring special data between App and Firmware using the api calls. This is a little different to the other Special Stations that use fixed width parameters. I did this because I wanted to support server names, in addition to IP addresses, and the On/Off commands can be arbitrary length.
In Firmware, I have extended the SpecialStationData structure from …
=> Added support for HTTP Stations

www/js/main.js
Hey Ray/Samer,
Apologies for the delay in getting this PR in. Things have just been a bit manic at work and home. I have created this PR against both Firmware and App to correct for a buffer overrun if a user specifies a very long HTTP On/Off command in Station Settings dialogue.
PR1: App - Introduced logic to keep track of the URI Encoded length of the HTTP Station configuration parameters. I ensure that the User's configuration is constrained such that they cannot save a set of parameters that would overrun either Firmware TMP_BUFFER or SpecialStationData. i.e. they have around 240 character to play with when encoded (say 2/3rds of that in clear text) for on/off commands. See below for screen shot.
PR2: Firmware - Current findKeyVal logic will truncate a Value string if longer than …
=> Fix buffer overrun when storing long station configuration

www/js/main.js
Samer , I have seen on the forum [here](https://opensprinkler.com/forums/topic/bug-http-stationos-2-32-1-7-url-length-limitation-causes-erratic-behavior/#post-51161) that the Station Special Data can be corrupted when importing configuration from file.
Looking at the code, I can see that the App import function does not uri encode the special data before sending to OS. This means that "&" characters in the on/off commands for http stations are not escaped and get misinterpreted by Firmware server.cpp as delimiters.
I probably should have picked this up during the original testing as I dont think any of the other special station config requires encoding.
Might be worth looking at some of the other fields in importConfig() to see if they also require encoding.
=> Fix import routine to uri encode station special data

package-lock.json, package.json, www/index.html, www/js/home.js, www/js/main.js, www/js/map.js, www/map.html
Adds support to view and select personal weather stations (PWS) when provided an API key. This is is for PWS owners only.
This PR also updates all packages to the latest version and changes all indentation to tabs for all files (due to inconsistencies in the PR diff). Due to this, please ignore whitespace when diffing. Github has an option for this under the gear icon at the top. 
This will be used in conjunction with https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/70 and https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/72.
=> Restore ability to select PWS when providing an API key

www/js/main.js
By using `call` the function is immediately called and the value of `useFailOverMethodForRefresh` gets set to true. This uses bind so the parameters we want are set but the function is only called if needed.
=> Fix bug causing updateController to never be used for refresh

www/js/main.js
Since the `region` field in the response is now always empty, this value was always being set to `true`.
=> Don't set isMetric based on region field in forecast

www/js/main.js
Hey Samer, as per Slack. I had a go at amending the import routine. I left `wtkey` alone as it looks like it will fall under `wto` going forward. Let me know if anything needs changing.
=> Add wto and ifkey to imports

www/css/main.css, www/js/main.js
Ensure App uses attribution associated with watering data in the System Diagnostic popup. Add attribution using weather data in the Forecast Page.
Linked to Weather Service PR: [#83](https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/83)
=> Split weather and watering attribution

www/js/main.js, www/js/map.js
Sorry for multiple updates in the one PR and I can split out if preferred:
- Use the "current" value of `#wtkey` rather than the saved version from `controller.settings.wto.key` in order to display PWS stations on map. This avoids the need for having to save the setting before it can take effect.
- Show PWS ID rather than location name (i.e. "ILONDON654" rather than "London") in the PWS Info Box when selecting a PWS "blue" dot. This is helpful when there are more than one PWS in close proximity.
- Move the zoom controls to the other side of the map to avoid overlapping with the main App control box.
=> Enhance map with WUnderground

www/js/main.js
Fix for ‘Thr’ abbreviation of Thursday, compared with standard abbreviation of ‘Thu’ (line 12169).
=> Thursday abbreviation typo

www/js/main.js
I'm adding support for reading & modifying the station groups ids, which is not yet merged into the OpenSprinkler firmware but hopefully will be soon (see https://github.com/OpenSprinkler/OpenSprinkler-Firmware/pull/171 + another PR to come).
Since these changes keep compatibility with the existing firmware, I thought I'd submit this one early. Compatibility is kept by giving every station a default group id of zero, which is equivalent to just not having groups.
Screenshot of the field to edit the station id in zone settings:
I'm not familiar with the UI library the app uses, so I just copied the station field name and un-bolded the text inside the input. A much thinner field that aligns with the checkboxes (group ids go from only 0 to 15) would be ideal, but I didn't know how to make …
=> Add support for grouped stations

www/css/main.css
I'm combining tsikishome's work in [the forum thread](https://opensprinkler.com/forums/topic/stations-view-in-two-rows/) with my query selector so that mobile view is unchanged but any wide enough monitor will display 2 columns.
I don't think we need `margin: 0;` on the `:not(input):not(textarea)` selector so I didn't include it. I hope I'm correct.
Closes #119
=> Two column view: tsikishome's changes + media query

config.xml, package.json, www/js/main.js
- Bump version to 2.4.2 using `grunt bump` task
- Note: I am seeing some Cloudflare caching issues when loading betaui. Recently added features are not appearing. Please see video for more info
https://github.com/user-attachments/assets/c4fdf276-e253-498c-b822-a50c69a97f96
=> chore(vers): bump version to 2.4.2

.gitignore, Gruntfile.js, build/firmware/.gitignore, config.xml, package.json, www/js/modules/ui-dom.js
- Update the gruntfile task `compress:makeFW` to properly include the new `/vendor-js` folder
- Bumps version to 2.4.5
- Adds `/build` to `.gitignore`
- ⚠️ I noticed that the transifx tasks in gruntfile will be broken until we update them with the new paths! Will make a gh issue about that problem.
=> chore(deploy): fix grunt makeFW command

www/js/modules/dates.js, www/js/modules/logs.js
- Fixes [issue #195 with station grouping](https://github.com/OpenSprinkler/OpenSprinkler-App/issues/195) in log view throwing exception
- Updates `Dates.dateToString` to gracefully return `--` when undefined date is passed
- Refactors log view `prepTable` logic to properly set station name when grouping is station
- Updates `sortData` to properly assign endDate value when grouping is station
https://github.com/user-attachments/assets/aaba909f-5b92-4120-9adc-9e6985e2c702
=> fix(logs): station grouping issue 195

.github/workflows/app-store-connect.yml, .github/workflows/firebase-hosting.yml, .github/workflows/google-play.yml, www/js/main.js, www/js/modules/about.js, www/js/modules/dashboard.js, www/js/modules/errors.js
- Goal is to improve the generic uncaught exception handling to display a modal for the user with basic info and add the ability to report the error via GitHub issues
- Extend all github workflow actions to set `OSApp.uiState.appVersion` variable
- Refactor about.js to use `OSApp.uiState.appVersion` variable
- Remove about.js steps from all github workflows, due to superseded by `OSApp.uiState.appVersion`
- Add `OSApp.currentDevice` details to issue markdown
https://github.com/user-attachments/assets/6dee6b32-c8ff-4182-b4da-fddbfab049ae
=> feat(error-handler): improve generic error handling

www/js/modules/options.js, www/js/modules/weather.js
- Add elvis operators to prevent undefined exception from weather.js while attempting to read `currentSession.controller.settings.wsp`
- Potential workaround/fix for https://github.com/OpenSprinkler/OpenSprinkler-App/issues/202
=> fix(issue-202): add elvis operators

www/js/modules/errors.js, www/js/modules/sites.js, www/js/modules/utils.js, www/js/modules/weather.js
- Adds a new error modal that is displayed when we detect malformed json returned from the /jc endpoint
- The modal suggests the user update their firmware, with links to the update guide and the settings recovery tool
- 💡 It would be nice to have a wiki guide page for the recovery tool with usage instructions. We could link there instead of to the tool.
- 💡 Would also be nice to offer the user a way to remove the problematic controller from their sites? Currently the app is not usable after displaying the modal.
https://github.com/user-attachments/assets/9494bd29-7fff-43a7-ad04-4bda0daaaeda
=> feat(error-handler): malformed json error modal

www/js/modules/dashboard.js, www/js/modules/logs.js, www/js/modules/options.js, www/js/modules/programs.js, www/js/modules/stations.js, www/js/modules/status.js
- Resolves issue #215 
- Displays station/zone number next to station name everywhere station name is displayed (dashboard, preview programs, log table, log timeline, edit program, edit station, footer status)
- Controlled by a new option `showStationNumber` which is stored in local storage
- Refactors many places where station name is retrieved to use `Stations.getName(stationId)` rather than directly reading the `currentSession.controller.stations.snames` array
https://github.com/user-attachments/assets/7c6136bc-0758-4333-95d7-581e3516f4b7
=> feat(station-number): display zone number with station name

www/js/modules/weather.js
- Resolves request to use elvis operators rather than early return
- Allows weather component to be displayed properly while preventing crashes with older fw controllers
=> fix(weather): use elvis operator rather than early return

www/js/modules/logs.js, www/js/modules/utils.js, www/locale/messages_en.po
- compute flow rate using flow pulse rate factor
- store flow rate in log entries
- display flow rate column in log tables
- expose helper to convert flow rate to volume
- add English locale key for `Flow Rate`
- `npm run lint` *(fails: Cannot find package 'globals')*
- `npm test` *(fails: EHOSTUNREACH registry.npmjs.org)*
=> Add flow rate to logs table

www/js/modules/programs.js
- ensure jQuery Mobile select menus for weekday selection are destroyed when a program collapsible is closed
=> Fix weekly day selection glitch

www/js/main.js, www/js/modules/errors.js
- Temporarily remove the gh create issue button until we can figure out how to get full stack traces sent up
- Adds an  `Ignore All` button which will update the app session (uiState.ignoreAllErrors) to prevent the modal appearing again.
- Ignore All is reset each time the app is launched.
https://github.com/user-attachments/assets/70aeaf95-a73a-464e-a81e-97f522990ef5
=> fix(errors): remove gh create issue button, add ignore all button

www/js/modules/ui-dom.js
- ensure metric and 24-hour settings load regardless of `mobileinit` timing
- `npm test` *(fails: ChromeHeadless not found)*
=> Fix metric/time settings not loading

config.xml, res/android/network_security_config.xml
I'm using a custom CA to issue SSL certificates for my home services, including OpenSprinkler-PI.
On Android, user installed CA certificates are not picked up by Apps per defaut:
https://developer.android.com/privacy-and-security/security-config
and
https://developer.android.com/privacy-and-security/security-config#base-config
This change adds a network-security-config to the Android App, that allows SSL connections to services which use a certificate that was issued by a user installed CA
=> allow user installed CAs
