www/js/main.js

Hey Samer, this is to correct for issue [here](https://github.com/OpenSprinkler/OpenSprinkler-App/issues/53#issuecomment-441368139).
The problem is that the Zimmerman Adjustment dialog is showing metric values for imperial locations (e.g. US) when using Yahoo Weather api.
Basically, I had assumed a Weather Underground weather structure and format that is not quite the same when using Yahoo.:
- region is held in different places:  ```weather.forcast.region``` when using WUnderground and ```weather.region``` when using Yahoo
- region content is two digit Country Code when using WUnderground but Country Name when using Yahoo
I refactored as follows:
1) Shift all of the "three country" checks into the updateXXXWeather() routines as they are api specific
2) Consolidated formatting of temp and …

Fix zimmerman when using Yahoo for weather

---

www/js/main.js

Fx initialisation of isMetric

---

www/js/main.js

This solution isn't very pretty, but I couldn't think of a cleaner way to do it. Let me know if you can think of a better way to do it.

Error when saving settings if baseETo is not set

---

www/css/main.css
www/js/main.js

This reflects some of the more recent weather service enhancements into the App System Diagnostic popup. It tries to group information more intuitively and provide error messages rather than codes.
Note that this shortens many of the item titles so that they can fit on one line (using iPhone 6 as target). This breaks some of the localisation translations. It looks like the popup is c.30% localised at the moment so let me know if this is a problem and I can revert some of them.

Update System Diagnostic popup

---

www/js/main.js

@rayshobby Ray, I haven't tested this recently and may need a few tweaks, e.g. version number in the Import handler. Hope it helps.

Allow config of MQTT server and port

---

www/js/main.js

Related to https://github.com/OpenSprinkler/OpenSprinkler-Firmware/pull/133
Not tested

Mqtt: Allow to connect with username and password

---

www/js/main.js

I've verified that the assets load as expected over HTTPS. Should close #103

Use HTTPS URLs for OpenWeatherMap Assets

---

www/js/analog.js

Fix sensor values format on front page

---

www/js/main.js

- Change single quotes to double quotes to prevent build warning introduced in https://github.com/OpenSprinkler/OpenSprinkler-App/pull/149

chore(quotes): fix quotation to meet style

---

.github/PULL_REQUEST_TEMPLATE.md
.husky/pre-commit
package-lock.json
package.json
www/js/main.js

- Add PR template with suggested fields (changes proposed and demo video/screenshots)
- Add [husky](https://typicode.github.io/husky/) to the project and configure it to run `npx grunt` any time a developer attempts to `git commit`
- This change allows early feedback of code/style/syntax errors that must be corrected before the `test` github workflow fails the PR
https://streamable.com/9isycb
🤔 Github is only allowing video attachments of <= 10MB in size

chore(dev-qol): developer quality of life improvements

---

.husky/pre-commit
README.md
package-lock.json
package.json
www/js/main.js

- Add `lint-staged` to automatically sort the package.json file during a `git commit`. Note that this PR contains the newly sorted package.json file.
- Add `http-server` and wire up the `npm start` script to launch a local dev web server on port 8080
- Update project `README.md` file with more details for developers. I want to continue to expand this area as I've found very little documentation for new devs on the project.
- Note that this PR includes some minor syntax/formatting changes to main.js that I failed to add during my last PR

chore(dev): developer quality of life improvements 2

---

README.md

- Reformat and modernize the readme file
- Add sections for troubleshooting, contribution, grunt tasks, etc
- Add license badges
https://github.com/user-attachments/assets/c398b984-abeb-4ea5-92a3-6b8d583eca2f

chore(readme): update readme file

---

Gruntfile.js
firebase.json

- Properly document sites in firebase config to allow CLI deployment
- Update Grunt deployment scripts to properly deploy beta and prod UI

Fix firebase hosting config and update deployment scripts to Firebase

---

config.xml
package-lock.json
package.json
www/js/modules/ui-dom.js

- Previously, only the first log table had sorting enabled. Datatables was being instantiated based on a single table id, rather than a class applying to multiple tables.
- Bumps version to 2.4.6
https://github.com/user-attachments/assets/f8b5608a-ce91-45bc-a28c-b024bd56ed73

fix(logs): enable sorting on all tables

---

.github/workflows/firebase-hosting.yml
firebase.json

- Deployment to Firebase failed after merge and this attempts to fix that by providing a blank channelId.

Attempt fix for deployment on merge

---

www/index.html

- Hoping to fix the warning Chrome shows about the apple prefixed meta tag

Add recommended vendor neutral PWA capable meta

---

.github/workflows/firebase-hosting.yml
www/js/modules/programs.js
www/js/modules/ui-dom.js

- Modifies the Firebase Hosting script to allow deployments to beta and prod from Github

Add manual deployment for beta and prod environments

---

README.md

- Fix minor issues such as the version badge which is now based on the release rather than the package.json

Fix minor readme issues

---

www/js/modules/ui-dom.js

- Remove "Manual Mode" from footer menu
- See Slack convo for details: https://openthingsio.slack.com/archives/C3639602E/p1738183849841029

fix(manual-mode): remove menu option for manual mode

---

www/js/modules/options.js
www/js/modules/weather.js

- Changed the main page weather forecast to now pull from the weather provider given in settings. 
*Note*: Will only function with the pending weather changes [PR 159](https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/159)

Weather forecast changes with provider.

---

www/js/main.js
www/js/modules/options.js
www/js/modules/weather.js

Fix base eto detection

---

.editorconfig
.github/workflows/ios-deploy.yml
.vscode/settings.json
config.xml
package-lock.json
package.json

Add iOS workflow

---

www/js/hasher.js

Add back hasher

---

www/js/main.js

- Removes the generic exception handler that displays an `alert()`
- I left the `console.error` line as it may be useful for future debugging

fix(alert): remove error alert

---

www/css/main.css
www/js/modules/firmware.js
www/js/modules/programs.js
www/js/modules/sites.js
www/js/modules/ui-dom.js

- Adds functionality to Programs page to conditionally hide disabled programs, based on the "Show Disabled" option/setting
- Adds a message to the bottom of the program list indicating that programs were hidden, and how to view them
- Extends the `submitProgram` functions to properly trigger the page's `programrefresh` event which re-renders the list
https://github.com/user-attachments/assets/d25d57dd-4833-406f-aaf5-60d30461dab7

feat(programs): hide disabled programs

---

www/js/modules/programs.js

- Properly expand the program edit component with the selected preview program
- Most of the logic already existed but a bug was preventing it from firing
- This resolves https://github.com/OpenSprinkler/OpenSprinkler-App/issues/204
https://github.com/user-attachments/assets/16e44827-d637-4877-8e05-a5f6d111e254

fix(programs): expand tapped preview program id

---

www/css/main.css
www/js/modules/programs.js

- Minor ux improvements to styling of preview programs timeline
- Font size for program name reduced
- Added cursor style of pointer to indicate the program timeline block is tappable

fix(programs): minor styling improvements

---

www/js/modules/logs.js
www/js/modules/programs.js
www/js/modules/weather.js

- Resolves app crashes when using firmware v2.1.4

fix(wto): resolve app crashes w/ fw 2.1.4 and missing wto

---

.github/workflows/tag-version.yml

- add GitHub workflow to tag releases using GitVersion
- `npm test` *(fails: connect EHOSTUNREACH)*

Add version tagging workflow
